# Generated by Django 5.0.4 on 2026-04-09 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                ("hotel_name", models.TextField()),
                (
                    "hotel_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "hotel_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("room_details", models.TextField()),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("guest_name", models.CharField(max_length=255)),
                ("amount_usdt", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount_rub", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "cost_price_usdt",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Ожидание оплаты"),
                            ("paid", "Оплачено"),
                            ("booking", "В процессе бронирования"),
                            ("voucher_issued", "Ваучер готов"),
                            ("failed", "Ошибка"),
                            ("refunded", "Возврат"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("rate_key", models.CharField(max_length=255)),
                (
                    "emerging_booking_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("voucher_url", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "from_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("to_address", models.CharField(max_length=255)),
                ("amount_usdt", models.DecimalField(decimal_places=2, max_digits=10)),
                ("confirmed", models.BooleanField(default=False)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.order",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Hotel",
        ),
    ]
