# Generated by Django 5.0.4 on 2026-04-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_order_transaction_delete_hotel"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelCache",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("stars", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Кэш отеля",
                "verbose_name_plural": "Кэш отелей",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Заказ", "verbose_name_plural": "Заказы"},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"verbose_name": "Транзакция", "verbose_name_plural": "Транзакции"},
        ),
    ]
