# Generated by Django 5.0.4 on 2026-04-16 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_hotelcache_alter_order_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelStatic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hotel_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID отеля в API"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("star_rating", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="HotelImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url_template", models.URLField()),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.hotelstatic",
                    ),
                ),
            ],
        ),
    ]
