# Generated by Django 5.0.4 on 2026-04-16 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_hotelstatic_hotelimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HotelImage",
        ),
        migrations.DeleteModel(
            name="HotelStatic",
        ),
    ]
