# Generated by Django 5.0.4 on 2026-04-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_hotelstatic_hotelimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelstatic",
            name="kind",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
