# Generated by Django 5.0.4 on 2026-04-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_hotelstatic_kind"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="amount_rub",
        ),
        migrations.AlterField(
            model_name="order",
            name="rate_key",
            field=models.TextField(),
        ),
    ]
