# Generated by Django 5.0.4 on 2026-04-19 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_order_amount_rub_alter_order_rate_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelstatic",
            name="hid",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Числовой HID"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="amount_rub",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="network",
            field=models.CharField(
                choices=[("TRC20", "TRON (TRC-20)"), ("ERC20", "Ethereum (ERC-20)")],
                default="TRC20",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="raw_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="amount_usdt",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="order",
            name="cost_price_usdt",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="order",
            name="guest_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount_usdt",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="tx_hash",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Хэш транзакции",
            ),
        ),
    ]
