# Generated by Django 5.0.4 on 2026-04-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_hotelstatic_hid_order_amount_rub_transaction_network_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Ожидание оплаты"),
                    ("paid", "Оплачено"),
                    ("pending", "В обработке (ожидание ID)"),
                    ("booking", "В процессе бронирования"),
                    ("voucher_issued", "Ваучер готов"),
                    ("failed", "Ошибка"),
                    ("cancelled", "Отменено"),
                    ("refunded", "Возврат"),
                ],
                default="pending_payment",
                max_length=20,
            ),
        ),
    ]
