# Generated by Django 5.0.4 on 2026-04-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelstatic",
            name="check_in_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="hotelstatic",
            name="check_out_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="hotelstatic",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="hotelstatic",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="hotelstatic",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
