# Generated by Django 5.0.4 on 2026-04-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_hotelstatic_check_in_time_hotelstatic_check_out_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="room_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
