# Generated by Django 5.0.4 on 2026-04-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_order_room_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=50)),
                (
                    "country_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
