# Generated by Django 5.0.4 on 2026-04-26 11:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_region"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Region",
        ),
    ]
