# Generated by Django 5.0.4 on 2026-04-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_delete_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelstatic",
            name="amenities_json",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Удобства (JSON)"
            ),
        ),
        migrations.AddField(
            model_name="hotelstatic",
            name="distance_center",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hotelstatic",
            name="facts_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hotelstatic",
            name="metapolicy_extra_info",
            field=models.TextField(blank=True, null=True),
        ),
    ]
