# Generated by Django 5.0.4 on 2026-04-27 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_hotelstatic_amenities_json_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotelstatic",
            name="amenities_json",
        ),
        migrations.RemoveField(
            model_name="hotelstatic",
            name="distance_center",
        ),
        migrations.RemoveField(
            model_name="hotelstatic",
            name="facts_json",
        ),
        migrations.RemoveField(
            model_name="hotelstatic",
            name="metapolicy_extra_info",
        ),
    ]
