# Generated by Django 5.0.4 on 2026-04-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_remove_hotelstatic_amenities_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelstatic",
            name="amenities_list",
            field=models.TextField(
                blank=True, help_text="Список удобств через запятую", null=True
            ),
        ),
        migrations.AddField(
            model_name="hotelstatic",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hotelstatic",
            name="country_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="hotelstatic",
            name="hotel_chain",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hotelstatic",
            name="important_info",
            field=models.TextField(blank=True, null=True),
        ),
    ]
