# Generated by Django 5.0.4 on 2026-04-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_hotelstatic_amenities_list_hotelstatic_city_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hotelstatic",
            options={
                "verbose_name": "Статичные данные отеля",
                "verbose_name_plural": "Статичные данные отелей",
            },
        ),
        migrations.AlterField(
            model_name="hotelstatic",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="hotelstatic",
            name="amenities_list",
            field=models.TextField(
                blank=True, null=True, verbose_name="Список всех удобств"
            ),
        ),
        migrations.AlterField(
            model_name="hotelstatic",
            name="check_in_time",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Время заезда"
            ),
        ),
        migrations.AlterField(
            model_name="hotelstatic",
            name="check_out_time",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Время выезда"
            ),
        ),
        migrations.AlterField(
            model_name="hotelstatic",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="hotelstatic",
            name="country_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Код страны"
            ),
        ),
        migrations.AlterField(
            model_name="hotelstatic",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание (HTML)"
            ),
        ),
        migrations.AlterField(
            model_name="hotelstatic",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="hotelstatic",
            name="hotel_chain",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Сеть отелей"
            ),
        ),
        migrations.AlterField(
            model_name="hotelstatic",
            name="hotel_id",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="ID отеля (строковый)"
            ),
        ),
        migrations.AlterField(
            model_name="hotelstatic",
            name="important_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="Важная информация (правила)"
            ),
        ),
        migrations.AlterField(
            model_name="hotelstatic",
            name="kind",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Тип объекта (отель, апарт и т.д.)",
            ),
        ),
        migrations.AlterField(
            model_name="hotelstatic",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Широта"),
        ),
        migrations.AlterField(
            model_name="hotelstatic",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Долгота"),
        ),
        migrations.AlterField(
            model_name="hotelstatic",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Название отеля"
            ),
        ),
        migrations.AlterField(
            model_name="hotelstatic",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Телефон"
            ),
        ),
        migrations.AlterField(
            model_name="hotelstatic",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Почтовый индекс"
            ),
        ),
        migrations.AlterField(
            model_name="hotelstatic",
            name="star_rating",
            field=models.IntegerField(default=0, verbose_name="Количество звезд"),
        ),
    ]
