# Generated by Django 5.0.4 on 2026-04-28 09:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_hotelstatic_options_alter_hotelstatic_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hotelstatic",
            options={},
        ),
    ]
