# Generated by Django 5.2.8 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_hotelnearbycache"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="access_token_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
