# Generated by Django 5.2.14 on 2026-06-15 11:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_order_access_token_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='voucher_status',
            field=models.CharField(choices=[('not_received', 'Не получен'), ('voucher_received', 'Получен от партнёра'), ('voucher_generated', 'Сгенерирован наш ваучер'), ('voucher_sent', 'Отправлен клиенту'), ('failed', 'Ошибка обработки')], default='not_received', max_length=30),
        ),
        migrations.CreateModel(
            name='HotelRoomStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_ext_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Идентификатор сопоставления (ext)')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа номера')),
                ('amenities', models.JSONField(blank=True, default=list, verbose_name='Удобства в номере')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.hotelstatic', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Статика номера',
                'verbose_name_plural': 'Статика номеров',
            },
        ),
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_email', models.CharField(max_length=255, verbose_name='Отправитель')),
                ('subject', models.CharField(blank=True, max_length=512, verbose_name='Тема письма')),
                ('body', models.TextField(blank=True, verbose_name='Тело письма (текст/html)')),
                ('original_file', models.FileField(blank=True, null=True, upload_to='inbound_emails/%Y/%m/%d/', verbose_name='Файл письма/Вложение')),
                ('parsed_booking_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Распарсенный ID брони')),
                ('processing_status', models.CharField(choices=[('pending', 'В очереди'), ('processed', 'Успешно обработано'), ('failed', 'Ошибка обработки'), ('manual', 'Требует ручной обработки')], default='pending', max_length=20, verbose_name='Статус обработки')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Текст ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_emails', to='core.order', verbose_name='Связанный заказ')),
            ],
            options={
                'verbose_name': 'Входящее письмо',
                'verbose_name_plural': 'Входящие письма',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=32, null=True, verbose_name='Старый статус')),
                ('new_status', models.CharField(max_length=32, verbose_name='Новый статус')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина / Комментарий')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор изменений')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История статуса заказа',
                'verbose_name_plural': 'История статусов заказов',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_template', models.URLField(verbose_name='Ссылка на фото номера')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.hotelroomstatic', verbose_name='Тип номера')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_voucher_file', models.FileField(upload_to='vouchers/partner/%Y/%m/%d/', verbose_name='Оригинальный ваучер партнёра')),
                ('generated_voucher_file', models.FileField(blank=True, null=True, upload_to='vouchers/client/%Y/%m/%d/', verbose_name='Наш сгенерированный ваучер')),
                ('sent_to_email', models.EmailField(max_length=254, verbose_name='Email отправки')),
                ('status', models.CharField(choices=[('not_received', 'Не получен'), ('voucher_received', 'Получен от партнёра'), ('voucher_generated', 'Сгенерирован наш ваучер'), ('voucher_sent', 'Отправлен клиенту'), ('failed', 'Ошибка обработки')], default='voucher_received', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен клиенту')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='core.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Документ ваучера',
                'verbose_name_plural': 'Документы ваучеров',
            },
        ),
    ]
