# Generated by Django 5.2.14 on 2026-06-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_order_voucher_status_hotelroomstatic_inboundemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='partner_order_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
