"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import secrets
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=""):
    value = os.environ.get(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", env_bool("DEBUG", False))

RUNNING_TESTS = any(arg == "test" or arg.startswith("test.") for arg in sys.argv)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG or RUNNING_TESTS:
        SECRET_KEY = secrets.token_urlsafe(50)
    else:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set when DJANGO_DEBUG=false")

ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    "travel.aifory.pro,localhost,127.0.0.1,[::1],testserver",
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "corsheaders",
    
    "core"
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],

    # Добавляем защиту от спама (Rate Limiting)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',  
        'rest_framework.throttling.UserRateThrottle',  
        'rest_framework.throttling.ScopedRateThrottle', 
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',      
        'user': '1000/day',     
        'financial': '5/min',  
    }
}
WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Считываем конфигурацию базы данных из .env
DB_NAME = os.environ.get("DB_NAME", "hotel_db")
DB_USER = os.environ.get("DB_USER", "postgres")
DB_PASSWORD = os.environ.get("DB_PASSWORD", "")
DB_HOST = os.environ.get("DB_HOST", "127.0.0.1")
DB_PORT = os.environ.get("DB_PORT", "5432")

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
        'CONN_MAX_AGE': 60,
    }
}

# Railway/Heroku-style single-URL override
_DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
if _DATABASE_URL:
    import dj_database_url

    DATABASES["default"] = dj_database_url.parse(
        _DATABASE_URL, conn_max_age=60, ssl_require=False
    )


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True


ETG_KEY_ID = os.environ.get("ETG_KEY_ID", "").strip()
ETG_KEY = os.environ.get("ETG_KEY", "").strip()
ETG_BASE_URL = os.environ.get("ETG_BASE_URL", "").strip()
if not ETG_BASE_URL:
    if DEBUG or RUNNING_TESTS:
        ETG_BASE_URL = "https://api-sandbox.worldota.net/api/b2b/v3"
    else:
        raise ImproperlyConfigured("ETG_BASE_URL must be set when DJANGO_DEBUG=false")
if not DEBUG and not RUNNING_TESTS and "sandbox" in ETG_BASE_URL.lower():
    raise ImproperlyConfigured("ETG_BASE_URL must be production URL when DJANGO_DEBUG=false")

ETG_WEBHOOK_SECRET = os.environ.get("ETG_WEBHOOK_SECRET", "").strip()
if not ETG_WEBHOOK_SECRET and not DEBUG and not RUNNING_TESTS:
    raise ImproperlyConfigured("ETG_WEBHOOK_SECRET must be set when DJANGO_DEBUG=false")

TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "").strip()
TELEGRAM_ADMIN_CHAT_ID = os.environ.get("TELEGRAM_ADMIN_CHAT_ID", "").strip()
if not TELEGRAM_BOT_TOKEN and not DEBUG and not RUNNING_TESTS:
    raise ImproperlyConfigured("TELEGRAM_BOT_TOKEN must be set when DJANGO_DEBUG=false")


ABCEX_API_KEY = os.environ.get("ABCEX_API_KEY", "").strip()
ABCEX_SECRET_KEY = os.environ.get("ABCEX_SECRET_KEY", "").strip()
ABCEX_WALLET_ID = os.environ.get("ABCEX_WALLET_ID", "").strip()
# Прокси со статичным "чистым" IP для обхода WAF ABCEX (формат: http://user:pass@host:port)
ABCEX_PROXY_URL = os.environ.get("ABCEX_PROXY_URL", "").strip()
# Тестовый режим оплаты: подтверждает оплату без реальной крипты (для сертификации ETG).
# ВКЛЮЧАТЬ ТОЛЬКО на тестовой/сертификационной среде. На проде должно быть false.
ALLOW_TEST_PAYMENT = env_bool("ALLOW_TEST_PAYMENT", False)
# Корпоративный email, на который ETG присылает ваучер с net-ценой.
ETG_VOUCHER_EMAIL = os.environ.get("ETG_VOUCHER_EMAIL", "voucher@aifory.pro").strip()

_REQUIRED_PROD_SECRETS = {
    "ETG_KEY_ID": ETG_KEY_ID,
    "ETG_KEY": ETG_KEY,
    "ABCEX_API_KEY": ABCEX_API_KEY,
    "ABCEX_SECRET_KEY": ABCEX_SECRET_KEY,
    "ABCEX_WALLET_ID": ABCEX_WALLET_ID,
}
if not DEBUG and not RUNNING_TESTS:
    _missing = sorted(name for name, value in _REQUIRED_PROD_SECRETS.items() if not value)
    if _missing:
        raise ImproperlyConfigured(
            "Required secrets must be set when DJANGO_DEBUG=false: "
            + ", ".join(_missing)
        )

PAYMENT_EXPIRATION_SECONDS = int(os.environ.get("PAYMENT_EXPIRATION_SECONDS", "1200"))
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.yandex.ru')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '465'))
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', True)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'voucher@aifory.pro')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Aifory Pro <voucher@aifory.pro>')



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ИСПРАВЛЕНО: Дефолт всегда False. ALL_ORIGINS = True разрешаем только если передали из env
CORS_ALLOW_ALL_ORIGINS = env_bool("CORS_ALLOW_ALL_ORIGINS", False)

# Список разрешенных доменов для фронтенда (например: https://my-hotel-app.com)
CORS_ALLOWED_ORIGINS = env_list("CORS_ALLOWED_ORIGINS", default=[])

SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", not DEBUG)
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", not DEBUG)
SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000" if not DEBUG else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", False)

CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
